
#pragma once

#include <ppl/std/inttypes.h>

enum XDTaskTypeEnum
{
	XD_EMPTY_TASK = 0,
	XD_NORMAL_TASK = 1, 
	XD_MULTI_HOP_TASK = 2, 
	XD_IUT_TASK = 3, 
	XD_EXE_TASK = 4,
	XD_POST_TASK = 5,
	XD_UPDATE_TASK = 6,
	XD_REDIRECT_TASK = 7,
	XD_CONFIG_TASK = 8,
	XD_CLIENTSIM_TASK = 9,
	XD_VASTSIM_TASK = 10,
	XD_VASTEXSIM_TASK = 11,
	XD_ClIENTEXSIM_TASK = 12,
	XD_CUSTOM_TASK = 13
};

const UINT8 XD_TYPE_REQUEST = 1;
const UINT8 XD_TYPE_RESPONSE = 2;
const UINT8 XD_TYPE_STATISTIC_REQUEST = 3;
const UINT8 XD_TYPE_STATISTIC_RESPONSE = 4;

// 7 - 支持新UA实现
const UINT16 XD_PROTOCOL_VERSION = 13;


